# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sathi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sathi
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'SVProgressHUD'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'GoogleSignIn'
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftyJSON'
  target 'SathiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SathiUITests' do
    # Pods for testing
  end

end
